# Generated by Django 3.2.8 on 2022-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(default='', null=True, upload_to='Img_Subject'),
        ),
    ]
